class Doctor {
  final String doctorImagePath;
  final String doctorName;
  final String doctorCategory;
  final num doctorRating;
  final String doctorFee;

  static List<Doctor> allDoctors = [
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor1.png',
      doctorName: 'Dr. John Doe',
      doctorCategory: 'Brain',
      doctorRating: 4.5,
      doctorFee: '\$200',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor2.png',
      doctorName: 'Dr. Jane Smith',
      doctorCategory: 'Heart',
      doctorRating: 4.7,
      doctorFee: '\$250',
    ),
    Doctor(
      // doctorImagePath: 'assets/images/doctor3.png',
      doctorName: 'Dr. Emily Johnson',
      doctorCategory: 'Skin',
      doctorRating: 4.6,
      doctorFee: '\$180',
    ),
  ];
  static const url =
      'https://media.istockphoto.com/id/1285124274/photo/middle-age-man-portrait.jpg?s=612x612&w=0&k=20&c=D14m64UChVZyRhAr6MJW3guo7MKQbKvgNVdKmsgQ_1g=';

  Doctor({
    this.doctorImagePath = url,
    required this.doctorName,
    required this.doctorCategory,
    required this.doctorRating,
    required this.doctorFee,
  });
}
